### ISSUE TITLE
 Installation error

### ISSUE THREAD

**Issue by rhnux** [riverfr0zen/graphene-mongo-extras#4]
Trying to install the following error occurs

```
pipenv install --dev git+https://github.com/riverfr0zen/graphene-mongo-extras.git\#egg\=graphene-mongo-extras
Installing git+https://github.com/riverfr0zen/graphene-mongo-extras.git#egg=graphene-mongo-extras…
Warning: You installed a VCS dependency in non-editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub-dependency functionality, specify that this dependency is editable.
Collecting graphene-mongo-extras from git+https://github.com/riverfr0zen/graphene-mongo-extras.git#egg=graphene-mongo-extras
  Cloning https://github.com/riverfr0zen/graphene-mongo-extras.git to /private/var/folders/6g/z4kxv6pj0z7ch89tws8zmym80000gn/T/pip-install-rp9dglqa/graphene-mongo-extras
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rodrigo/.local/share/virtualenvs/ms_concrete-BK818vFN/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/6g/z4kxv6pj0z7ch89tws8zmym80000gn/T/pip-install-rp9dglqa/graphene-mongo-extras/setup.py'

    ----------------------------------------

Error:  An error occurred while installing git+https://github.com/riverfr0zen/graphene-mongo-extras.git#egg=graphene-mongo-extras!
b'Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6g/z4kxv6pj0z7ch89tws8zmym80000gn/T/pip-install-rp9dglqa/graphene-mongo-extras/\n'
This is likely caused by a bug in graphene-mongo-extras. Report this to its maintainers.
✘ Installation Failed
```
### Versions:

```
pip --version
pip 18.1 from /Users/rodrigo/.local/share/virtualenvs/ms_concrete-BK818vFN/lib/python3.6/site-packages/pip (python 3.6)
```
```
pipenv --version
pipenv, version 2018.11.26
```
macOS Mojave 10.14.5

**Comment by riverfr0zen** [comment]
Hi, I think the issue is you are using an older version of pip. See https://stackoverflow.com/a/47594760/9475161

You should upgrade pip to >= 19.03 (e.g. from within your virtual environment `pip install --upgrade pip` )

Let me know if that still doesn't work (and post the error).

**Comment by riverfr0zen** [comment]
Also note that if you use --dev, it won't be available in a non-dev environment, so not sure you want to do that as the package would be required in your prod environments and such.

**Comment by rhnux** [comment]
It works!

I installed pip 19.1.1 and execute `pipenv install --dev git+https://github.com/riverfr0zen/graphene-mongo-extras.git\#egg\=graphene-mongo-extras`

```
pip --version
pip 19.1.1 from /Users/rodrigo/.local/share/virtualenvs/ms_concrete-BK818vFN/lib/python3.6/site-packages/pip (python 3.6)
```
<img width="728" alt="Screen Shot 2019-06-30 at 11 21 42" src="https://user-images.githubusercontent.com/26807888/60398003-cc982c00-9b29-11e9-8f5a-43d06bb11ab9.png">

thank a lots.
